#!/bin/bash
#
# ~/.bashrc_idun
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'

W='\[\033[37m\]'    # bright white foreground
G='\[\033[32m\]'    # green foreground
N='\[\033[0m\]'     # reset colors to default
PS1="${W}\u${N} ${G}\W${N}\$ "

. "/etc/profile.d/z88dk.sh"

load() {
    local arg="$1"

    # Check if argument starts with [a-z]:
    if [[ "$arg" =~ ^[a-z]: ]]; then
        # Looks like an idun device file; pass directly
        idunsh load "$arg"
        return
    fi
    # Otherwise, treat it as a filename in the current directory
    if [[ -f "$arg" ]]; then
        idunsh load "$arg"
    else
        echo "File not found: $arg" >&2
        return 1       # return non-zero to indicate failure
    fi
}

fcd() {
  local match
  match=$(fd . --type d | fzf --filter "$1" | head -n 1)

  [[ -z "$match" ]] && return 1

  if [[ -d "$match" ]]; then
    cd "$match"
  fi
}
