#!/bin/sh

post_install() {
    if [ ! -d "/home/idun/.config" ]; then
        mkdir -p /home/idun/.config
        chown idun:idun /home/idun/.config
    fi
    post_upgrade
}

post_upgrade() {
    if [ -f "/home/idun/.config/idunrc.toml" ]; then
        mv /home/idun/.config/idunrc.toml /home/idun/.config/idunrc.bak
    fi

    cp /usr/share/idun/idunrc.toml /home/idun/.config/idunrc.toml
    chown idun:idun /home/idun/.config/idunrc.toml

    if [ -f /home/idun/.bashrc ]; then
        cp /home/idun/.bashrc /home/idun/.bashrc.bak
    fi
    cp /usr/share/idun/bashrc /home/idun/.bashrc
    chown idun:idun /home/idun/.bashrc

    if [ -f /home/idun/.newshell ]; then
        cp /home/idun/.newshell /home/idun/.newshell.bak
    fi
    cp /usr/share/idun/newshell /home/idun/.newshell
    chown idun:idun /home/idun/.newshell
}
